[package]
name = "wold"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow= "1.0.58"
axum= "0.5.10"
serde_bytes= "0.11.6"
serde_json= "1.0.81"
tracing= "0.1.35"

[dependencies.serde]
version = "1.0.137"
features = ["derive"]

[dependencies.tokio]
version = "1.19.2"
features = ["macros", "net", "rt"]

[dependencies.tracing-subscriber]
version = "0.3.14"
features = ["env-filter"]
